# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd566a527792ae77ce214260f62edf8e65f9c0b557e01e2b3ad7c41b2ce58ec543265fa9a2afde7cf12cf7f6aca1ea046cce9ac2525bc9210a20ad434283b7fe

test:
  secret_key_base: 3268a0e5b5b038751679ef0bee77188b435092bb60d144352b0dafd589500640cde0698c77ac50a891ab00f2dd6a0f750d57b4aa7938cebdef7d6c494f9e6895

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: cd566a527792ae77ce214260f62edf8e65f9c0b557e01e2b3ad7c41b2ce58ec543265fa9a2afde7cf12cf7f6aca1ea046cce9ac2525bc9210a20ad434283b7fe
